
[profile.default]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"

[profile.ci-default-features]
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci-default-features.junit]
path        = "junit-default-features.xml"
report-name = "default-features"

[profile.ci-all-features]
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci-all-features.junit]
path        = "junit-all-features.xml"
report-name = "all-features"

[profile.ci-all-features-release]
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci-all-features-release.junit]
path        = "junit-all-features-release.xml"
report-name = "all-features-release"
