name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: /test-results-([a-z]*)-(.*)/ # artifact name: test-results-<toolchain>-<os>
        name: cargo nextest results $1 $2      # Name of the check run which will be created
        path: './**/junit-*.xml'               # Path to test results (inside artifact .zip)
        reporter: java-junit                   # Format of test results